// Code generated by MockGen. DO NOT EDIT.
// Source: douyin-service/domain (interfaces: InteractRepository)

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
        domain "douyin-service/domain"
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
)

// MockInteractRepository is a mock of InteractRepository interface.
type MockInteractRepository struct {
        ctrl     *gomock.Controller
        recorder *MockInteractRepositoryMockRecorder
}

// MockInteractRepositoryMockRecorder is the mock recorder for MockInteractRepository.
type MockInteractRepositoryMockRecorder struct {
        mock *MockInteractRepository
}

// NewMockInteractRepository creates a new mock instance.
func NewMockInteractRepository(ctrl *gomock.Controller) *MockInteractRepository {
        mock := &MockInteractRepository{ctrl: ctrl}
        mock.recorder = &MockInteractRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractRepository) EXPECT() *MockInteractRepositoryMockRecorder {
        return m.recorder
}

// AddCommentByUserId mocks base method.
func (m *MockInteractRepository) AddCommentByUserId(arg0, arg1 int64, arg2 string) (domain.CommentModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "AddCommentByUserId", arg0, arg1, arg2)
        ret0, _ := ret[0].(domain.CommentModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// AddCommentByUserId indicates an expected call of AddCommentByUserId.
func (mr *MockInteractRepositoryMockRecorder) AddCommentByUserId(arg0, arg1, arg2 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCommentByUserId", reflect.TypeOf((*MockInteractRepository)(nil).AddCommentByUserId), arg0, 
arg1, arg2)
}

// DeleteCommentById mocks base method.
func (m *MockInteractRepository) DeleteCommentById(arg0, arg1 int64) (domain.CommentModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "DeleteCommentById", arg0, arg1)
        ret0, _ := ret[0].(domain.CommentModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// DeleteCommentById indicates an expected call of DeleteCommentById.
func (mr *MockInteractRepositoryMockRecorder) DeleteCommentById(arg0, arg1 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCommentById", reflect.TypeOf((*MockInteractRepository)(nil).DeleteCommentById), arg0, arg1)
}

// FavoriteActionByUserId mocks base method.
func (m *MockInteractRepository) FavoriteActionByUserId(arg0, arg1 int64, arg2 int32) (bool, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FavoriteActionByUserId", arg0, arg1, arg2)
        ret0, _ := ret[0].(bool)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FavoriteActionByUserId indicates an expected call of FavoriteActionByUserId.
func (mr *MockInteractRepositoryMockRecorder) FavoriteActionByUserId(arg0, arg1, arg2 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteActionByUserId", reflect.TypeOf((*MockInteractRepository)(nil).FavoriteActionByUserId), arg0, arg1, arg2)
}

// GetCommentListByVideoId mocks base method.
func (m *MockInteractRepository) GetCommentListByVideoId(arg0 int64) ([]domain.CommentModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetCommentListByVideoId", arg0)
        ret0, _ := ret[0].([]domain.CommentModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetCommentListByVideoId indicates an expected call of GetCommentListByVideoId.
func (mr *MockInteractRepositoryMockRecorder) GetCommentListByVideoId(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommentListByVideoId", reflect.TypeOf((*MockInteractRepository)(nil).GetCommentListByVideoId), arg0)
}

// GetFavoriteListByUserId mocks base method.
func (m *MockInteractRepository) GetFavoriteListByUserId(arg0 int64) ([]domain.FavoriteListModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetFavoriteListByUserId", arg0)
        ret0, _ := ret[0].([]domain.FavoriteListModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetFavoriteListByUserId indicates an expected call of GetFavoriteListByUserId.
func (mr *MockInteractRepositoryMockRecorder) GetFavoriteListByUserId(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteListByUserId", reflect.TypeOf((*MockInteractRepository)(nil).GetFavoriteListByUserId), arg0)
}

// GetUser mocks base method.
func (m *MockInteractRepository) GetUser(arg0 int64) (domain.UserModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetUser", arg0)
        ret0, _ := ret[0].(domain.UserModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockInteractRepositoryMockRecorder) GetUser(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockInteractRepository)(nil).GetUser), arg0)
}

// GetVideoModelsById mocks base method.
func (m *MockInteractRepository) GetVideoModelsById(arg0 []int64) ([]domain.VideoModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetVideoModelsById", arg0)
        ret0, _ := ret[0].([]domain.VideoModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetVideoModelsById indicates an expected call of GetVideoModelsById.
func (mr *MockInteractRepositoryMockRecorder) GetVideoModelsById(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideoModelsById", reflect.TypeOf((*MockInteractRepository)(nil).GetVideoModelsById), arg0) 
}