// Code generated by MockGen. DO NOT EDIT.
// Source: douyin-service/domain (interfaces: InteractUsecase)

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
        domain "douyin-service/domain"
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
)

// MockInteractUsecase is a mock of InteractUsecase interface.
type MockInteractUsecase struct {
        ctrl     *gomock.Controller
        recorder *MockInteractUsecaseMockRecorder
}

// MockInteractUsecaseMockRecorder is the mock recorder for MockInteractUsecase.
type MockInteractUsecaseMockRecorder struct {
        mock *MockInteractUsecase
}

// NewMockInteractUsecase creates a new mock instance.
func NewMockInteractUsecase(ctrl *gomock.Controller) *MockInteractUsecase {
        mock := &MockInteractUsecase{ctrl: ctrl}
        mock.recorder = &MockInteractUsecaseMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInteractUsecase) EXPECT() *MockInteractUsecaseMockRecorder {
        return m.recorder
}

// FavoriteActionByUserId mocks base method.
func (m *MockInteractUsecase) FavoriteActionByUserId(arg0, arg1 int64, arg2 int32) (bool, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FavoriteActionByUserId", arg0, arg1, arg2)
        ret0, _ := ret[0].(bool)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FavoriteActionByUserId indicates an expected call of FavoriteActionByUserId.
func (mr *MockInteractUsecaseMockRecorder) FavoriteActionByUserId(arg0, arg1, arg2 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FavoriteActionByUserId", reflect.TypeOf((*MockInteractUsecase)(nil).FavoriteActionByUserId), arg0, arg1, arg2)
}

// GetFavoriteListByUserId mocks base method.
func (m *MockInteractUsecase) GetFavoriteListByUserId(arg0 int64) ([]domain.Video, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetFavoriteListByUserId", arg0)
        ret0, _ := ret[0].([]domain.Video)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetFavoriteListByUserId indicates an expected call of GetFavoriteListByUserId.
func (mr *MockInteractUsecaseMockRecorder) GetFavoriteListByUserId(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFavoriteListByUserId", reflect.TypeOf((*MockInteractUsecase)(nil).GetFavoriteListByUserId), arg0)
}