// Code generated by MockGen. DO NOT EDIT.
// Source: douyin-service/domain (interfaces: SocialRepository)

// Package mock_domain is a generated GoMock package.
package mock_domain

import (
        domain "douyin-service/domain"
        reflect "reflect"

        gomock "github.com/golang/mock/gomock"
)

// MockSocialRepository is a mock of SocialRepository interface.
type MockSocialRepository struct {
        ctrl     *gomock.Controller
        recorder *MockSocialRepositoryMockRecorder
}

// MockSocialRepositoryMockRecorder is the mock recorder for MockSocialRepository.
type MockSocialRepositoryMockRecorder struct {
        mock *MockSocialRepository
}

// NewMockSocialRepository creates a new mock instance.
func NewMockSocialRepository(ctrl *gomock.Controller) *MockSocialRepository {
        mock := &MockSocialRepository{ctrl: ctrl}
        mock.recorder = &MockSocialRepositoryMockRecorder{mock}
        return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialRepository) EXPECT() *MockSocialRepositoryMockRecorder {
        return m.recorder
}

// FollowActionByUserId mocks base method.
func (m *MockSocialRepository) FollowActionByUserId(arg0, arg1 int64, arg2 int32) (bool, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "FollowActionByUserId", arg0, arg1, arg2)
        ret0, _ := ret[0].(bool)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// FollowActionByUserId indicates an expected call of FollowActionByUserId.
func (mr *MockSocialRepositoryMockRecorder) FollowActionByUserId(arg0, arg1, arg2 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FollowActionByUserId", reflect.TypeOf((*MockSocialRepository)(nil).FollowActionByUserId), arg0, arg1, arg2)
}

// GetFollowListByUserId mocks base method.
func (m *MockSocialRepository) GetFollowListByUserId(arg0 int64) ([]domain.FollowListModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetFollowListByUserId", arg0)
        ret0, _ := ret[0].([]domain.FollowListModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetFollowListByUserId indicates an expected call of GetFollowListByUserId.
func (mr *MockSocialRepositoryMockRecorder) GetFollowListByUserId(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowListByUserId", reflect.TypeOf((*MockSocialRepository)(nil).GetFollowListByUserId), arg0)
}

// GetFollowerListByUserId mocks base method.
func (m *MockSocialRepository) GetFollowerListByUserId(arg0 int64) ([]domain.FollowListModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetFollowerListByUserId", arg0)
        ret0, _ := ret[0].([]domain.FollowListModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetFollowerListByUserId indicates an expected call of GetFollowerListByUserId.
func (mr *MockSocialRepositoryMockRecorder) GetFollowerListByUserId(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFollowerListByUserId", reflect.TypeOf((*MockSocialRepository)(nil).GetFollowerListByUserId), arg0)
}

// GetFriendListByUserId mocks base method.
func (m *MockSocialRepository) GetFriendListByUserId(arg0 int64) ([]domain.FollowListModel, error) {
        m.ctrl.T.Helper()
        ret := m.ctrl.Call(m, "GetFriendListByUserId", arg0)
        ret0, _ := ret[0].([]domain.FollowListModel)
        ret1, _ := ret[1].(error)
        return ret0, ret1
}

// GetFriendListByUserId indicates an expected call of GetFriendListByUserId.
func (mr *MockSocialRepositoryMockRecorder) GetFriendListByUserId(arg0 interface{}) *gomock.Call {
        mr.mock.ctrl.T.Helper()
        return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFriendListByUserId", reflect.TypeOf((*MockSocialRepository)(nil).GetFriendListByUserId), arg0)
}